---
sidebar: sidebar
permalink: use/report-sample.html
keywords: bluexp reports, data protection reports
summary: Look at a sample report and learn what the data is showing. 
---

= View a sample report
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
Look at a sample report and learn what the data is showing. 

You can generate only one report at a time. 

The title of the report, for example “Volumes (100)”, indicates the number of volumes included in the report. 
  
.Steps 

. From the BlueXP left nav, select *Storage* > *Reports*.

. Select *Create New Report*.

. From the Dashboard, you can search for a report name or the volume name. You can also sort data in columns to show only the data you want. 

. To learn what the columns mean, hover over some of the information:  

.. To learn the SVM name, hover over the “*I*” information icon next to the Volume name. 

.. To learn about failed reports, hover over the *Failed information* in the Last Report Status column. 

. View the report information: 
+
* *Maximum* > *Total Depth*: The greatest number of subdirectories nested within a directory in the volume. In the example, directory/subdirectory/subdirectory2, the depth is 2.

* *Maximum* > *Total Maximum Width*: The greatest number of items in the volume’s directories. An item is a file, subdirectory, symbolic link, or hard link.

* *Maximum* > *Longest Path*: The longest subdirectory path plus the file name in the volume.

* *Maximum* > *Directories*: The number of directories in the largest directory. 

* *Maximum* > *Files*: The number of files in the largest directory. There might be another directory with more files, but it isn’t the largest directory in the tree.

* *Access Time*: The last times that the files were accessed.

* *Change Time*: The last time that the file metadata, for example, permissions, was accessed.

* *Modify Time*: The last times that the content of the files was modified. 

* *Top 5 Failure Reasons*: The top 5 error reasons found during the volume scan. For example, a report might contain errors related to nonexistent or incorrect access permissions or the missing files. This type of error can impact the scan of the entire set of files and directories. After you view the list of errors, you can address the issues and run the report again.


* *Top 5 Directories and Files*: The directories having the top 5 largest number of directories or largest file sizes in the volume. 

. To return to the Reports Dashboard, select *Reports* in the breadcrumbs.  

=== View the Report distribution information 

You might need to check the change of data from one report date to another. You can do this using the Reports Distribution. 

.Steps 

. From the BlueXP left nav, select *Storage* > *Reports*.

. Select a report. 

. From the Actions menu on the right, select *View Reports Distribution*.  

. View the Reports distribution: 
+
* *Distribution Overtime (Total Size)*: Shows the size of the volume on different dates. 

* *Distribution Overtime (Total Items)*: Shows the number of files, folders, links, and directories on different dates. 

